"""Aggregate the Tier-3 sweep into the paper's table and frontier figure.

Reads the graded runs and emits, into paper/generated/:
  tier3_table.tex     — per-model copy-vs-waggle resolve rate, tokens, dollars
  tier3_frontier.dat  — cost-vs-quality frontier points (pgfplots)
"""

from __future__ import annotations

import json
import os
import sys
from collections import defaultdict

RUNS = os.environ.get("TIER3_RUNS", "/tmp/tier3/out/runs.json")
GEN = os.environ.get("TIER3_GEN", "paper/generated")

SHORT = {
    "claude-opus-4-1-20250805": "Opus 4.1",
    "claude-sonnet-4-5-20250929": "Sonnet 4.5",
    "claude-haiku-4-5-20251001": "Haiku 4.5",
    "gpt-5": "GPT-5",
    "gpt-5-mini": "GPT-5 mini",
    "gpt-4.1": "GPT-4.1",
    "gpt-4.1-mini": "GPT-4.1 mini",
    "gpt-4o": "GPT-4o",
    "gpt-4o-mini": "GPT-4o mini",
}
ORDER = list(SHORT)


def agg(runs):
    """(model, strategy) -> aggregate stats."""
    g = defaultdict(list)
    for r in runs:
        g[(r["model"], r["strategy"])].append(r)
    out = {}
    for k, rs in g.items():
        n = len(rs)
        out[k] = {
            "n": n,
            "resolved": sum(1 for r in rs if r["resolved"]),
            "rate": sum(1 for r in rs if r["resolved"]) / n if n else 0.0,
            "tokens": sum(r["in_tokens"] + r["out_tokens"] for r in rs) / n if n else 0,
            "dollars": sum(r["dollars"] for r in rs) / n if n else 0.0,
            "ops": sum(r["ops"] for r in rs) / n if n else 0.0,
            "patched": sum(1 for r in rs if r["patch"]),
        }
    return out


def main() -> int:
    runs = json.load(open(RUNS))
    a = agg(runs)
    models = [m for m in ORDER if (m, "copy") in a or (m, "waggle") in a]
    os.makedirs(GEN, exist_ok=True)

    # ---- overall headline
    tot = defaultdict(lambda: {"n": 0, "res": 0, "tok": 0, "usd": 0.0})
    for r in runs:
        t = tot[r["strategy"]]
        t["n"] += 1
        t["res"] += 1 if r["resolved"] else 0
        t["tok"] += r["in_tokens"] + r["out_tokens"]
        t["usd"] += r["dollars"]
    for s, t in tot.items():
        print(f"{s:6} n={t['n']:3} resolved={t['res']:3} ({t['res']/t['n']:.1%}) "
              f"mean_tokens={t['tok']//max(t['n'],1):6} total=${t['usd']:.2f}")

    c, w = tot.get("copy"), tot.get("waggle")
    save = (c["tok"] / w["tok"]) if (c and w and w["tok"]) else 0
    print(f"\ntoken reduction (copy/waggle): {save:.2f}x")

    # ---- table
    L = []
    L.append("% generated by bench/tier3/analyze.py (design doc 22 §4) — do not edit")
    L.append("\\begin{table*}[t]\n\\centering\\small")
    L.append("\\caption{SWE-bench Lite (%d instances, test-graded by the official harness). "
             "Both arms see the same candidate files; only the handoff differs. "
             "\\emph{copy} pastes every file; \\emph{waggle} hands one token per file and the "
             "subagent interrogates. Anthropic token counts are approximate (the API gateway "
             "strips usage); OpenAI counts are exact.}" % (a[(models[0], 'copy')]["n"]))
    L.append("\\label{tab:tier3}\n\\renewcommand{\\arraystretch}{1.15}")
    L.append("\\begin{tabular}{@{}llrrrrrrr@{}}\n\\toprule")
    L.append("& & \\multicolumn{3}{c}{\\textbf{copy}} & \\multicolumn{3}{c}{\\textbf{waggle}} & \\\\")
    L.append("\\cmidrule(lr){3-5}\\cmidrule(lr){6-8}")
    L.append("\\textbf{Model} & family & solved & tokens & \\$ & solved & tokens & \\$ & tok.\\,$\\downarrow$\\\\")
    L.append("\\midrule")
    for m in models:
        cc, ww = a.get((m, "copy")), a.get((m, "waggle"))
        if not (cc and ww):
            continue
        fam = "A" if m.startswith("claude") else "O"
        red = cc["tokens"] / ww["tokens"] if ww["tokens"] else 0
        L.append(
            f"{SHORT[m]} & {fam} & {cc['resolved']}/{cc['n']} & {cc['tokens']:.0f} & {cc['dollars']:.3f} "
            f"& {ww['resolved']}/{ww['n']} & {ww['tokens']:.0f} & {ww['dollars']:.3f} "
            f"& ${red:.1f}\\times$\\\\"
        )
    L.append("\\bottomrule\n\\end{tabular}\n\\end{table*}")
    open(f"{GEN}/tier3_table.tex", "w").write("\n".join(L) + "\n")

    # ---- frontier data (cost vs quality)
    with open(f"{GEN}/tier3_frontier.dat", "w") as f:
        f.write("tokens rate strategy model\n")
        for m in models:
            for s in ("copy", "waggle"):
                st = a.get((m, s))
                if st:
                    f.write(f"{st['tokens']:.0f} {st['rate']:.4f} {s} {SHORT[m].replace(' ','_')}\n")

    print(f"\nwrote {GEN}/tier3_table.tex and {GEN}/tier3_frontier.dat")
    return 0


if __name__ == "__main__":
    sys.exit(main())
