"""Aggregate the Tier-3 v4 sweep: did the fixes close the gaps? (doc 22 §4)

Four arms now. `waggle+gate` is waggle plus one thing no other arm can do:
the orchestrator reads the coverage receipt and refuses an answer the
consumer's own trail does not support. It never reads the answer and never
names the region — it only declines to accept a claim that is not backed.
"""

from __future__ import annotations

import json
import os
import sys
from collections import defaultdict

RUNS = os.environ.get("TIER3_RUNS4", "/tmp/tier3/out4/runs4.json")
GEN = os.environ.get("TIER3_GEN", "paper/generated")

SHAPES = ["text", "markdown", "code", "pdf", "voice", "video",
          "folder", "bigcode", "multihop", "reasoning",
          "bigtree_find", "bigtree_count"]
ARMS = ["copy", "reference", "waggle", "waggle+gate"]
LABEL = {"copy": "copy", "reference": "reference", "waggle": "waggle",
         "waggle+gate": "waggle+gate"}


def mean(xs):
    xs = list(xs)
    return sum(xs) / len(xs) if xs else 0.0


def agg(runs, pred=lambda r: True):
    g = defaultdict(list)
    for r in runs:
        if pred(r):
            g[r["arm"]].append(r)
    out = {}
    for a in ARMS:
        rs = g.get(a, [])
        out[a] = dict(
            n=len(rs),
            ok=mean(1 if r["correct"] else 0 for r in rs),
            tok=mean(r["in_tokens"] + r["out_tokens"] for r in rs),
            ing=mean(r["ingested"] for r in rs),
            usd=sum(r["dollars"] for r in rs),
            turns=mean(r["turns"] for r in rs),
            rej=sum(r.get("gate_rejections", 0) for r in rs),
        )
    return out


def main() -> int:
    runs = [r for r in json.load(open(RUNS)) if not r.get("transport_error")]
    print(f"v4 runs analysed: {len(runs)}\n")

    print("=== per shape (correct% | tokens | bytes ingested) ===")
    for s in SHAPES:
        a = agg(runs, lambda r, s=s: r["modality"] == s)
        print(f"  {s:10} " + "  ".join(
            f"{LABEL[x][:11]}={a[x]['ok']:.0%}/{a[x]['tok']:.0f}t/{a[x]['ing']:.0f}B" for x in ARMS))

    print("\n=== overall ===")
    a = agg(runs)
    for x in ARMS:
        print(f"  {LABEL[x]:12} correct={a[x]['ok']:.1%}  tokens={a[x]['tok']:.0f}  "
              f"ingested={a[x]['ing']:.0f}B  turns={a[x]['turns']:.1f}  ${a[x]['usd']:.2f}")
    c, w, g = a["copy"], a["waggle"], a["waggle+gate"]
    print(f"\n  gate rejections issued: {g['rej']}")
    print(f"  waggle+gate vs copy : accuracy {g['ok']:.1%} vs {c['ok']:.1%}   "
          f"tokens {c['tok']/max(g['tok'],1):.1f}x fewer   "
          f"bytes {c['ing']/max(g['ing'],1):.0f}x fewer")

    # The gate only bites where a contract exists (a --tree parent has none, and
    # bigtree deliberately carries none — see bench4.CONTRACT_ALL).
    TREE = ("folder", "bigtree_find", "bigtree_count")
    a2 = agg(runs, lambda r: r["modality"] not in TREE)
    print(f"\n=== where the gate can act (contract-bearing shapes) ===")
    for x in ARMS:
        print(f"  {LABEL[x]:12} correct={a2[x]['ok']:.1%}  tokens={a2[x]['tok']:.0f}  "
              f"ingested={a2[x]['ing']:.0f}B")

    # ---- paper table
    os.makedirs(GEN, exist_ok=True)
    L = ["% generated by bench/tier3/analyze4.py (doc 22 §4) — do not edit",
         "\\begin{table*}[t]\n\\centering\\small",
         f"\\caption{{Twelve artifact shapes, nine models, four turn-matched arms; {len(runs)} runs. "
         "Every arm answers the same (artifact, model) pairs, so the arms are \\emph{paired}. "
         "\\emph{waggle+gate} adds the one move no other arm can make: the orchestrator reads "
         "the coverage receipt and declines an answer the consumer\'s own trail does not "
         "support --- without reading the answer, and without naming the region. "
         "\\emph{ingest} is artifact bytes that entered the context window. "
         "Read the table for the \\emph{shape} of the failures, not for a winner: against the "
         "paste the token ties (13 paired wins to 15) at a thirty-second of the context; against "
         "a raw \\emph{path} --- given \\texttt{pdftotext} and \\texttt{ls}, so a fair baseline "
         "--- it wins 34 to 9. Two rows carry the argument: \\texttt{bigtree\\_count}, where a "
         "copy holding all 310\\,KB counts correctly only 61\\% of the time, and "
         "\\texttt{reasoning}, where our own gate makes things \\emph{worse}.}",
         "\\label{tab:tier3v4}\n\\renewcommand{\\arraystretch}{1.15}",
         "\\begin{tabular}{@{}l rr rr rr rr@{}}\n\\toprule",
         "& \\multicolumn{2}{c}{\\textbf{copy}} & \\multicolumn{2}{c}{\\textbf{reference}} "
         "& \\multicolumn{2}{c}{\\textbf{waggle}} & \\multicolumn{2}{c}{\\textbf{+gate}}\\\\",
         "\\cmidrule(lr){2-3}\\cmidrule(lr){4-5}\\cmidrule(lr){6-7}\\cmidrule(lr){8-9}",
         "\\textbf{Shape} & ok & ingest & ok & ingest & ok & ingest & ok & ingest\\\\",
         "\\midrule"]
    for s in SHAPES:
        st = agg(runs, lambda r, s=s: r["modality"] == s)
        if s in ("folder", "bigtree_find"):
            L.append("\\midrule")
        # `_` is a math-mode character in LaTeX; a bare `bigtree_count` in a
        # table cell halts the build with "Missing $ inserted".
        label = s.replace("_", r"\_")
        L.append(f"{label} & " + " & ".join(
            f"{st[x]['ok']:.0%}".replace("%", "\\%") + f" & {st[x]['ing']:.0f}" for x in ARMS) + "\\\\")
    L.append("\\midrule")
    L.append("\\textbf{all} & " + " & ".join(
        f"\\textbf{{{a[x]['ok']:.0%}}}".replace("%", "\\%") + f" & \\textbf{{{a[x]['ing']:.0f}}}"
        for x in ARMS) + "\\\\")
    L += ["\\bottomrule\n\\end{tabular}\n\\end{table*}"]
    open(f"{GEN}/tier3_gate.tex", "w").write("\n".join(L) + "\n")
    # Where copy actually breaks: an artifact too big for the window is not a
    # transport failure, it is the strategy failing. Say how often.
    ov = [r for r in json.load(open(RUNS))
          if r["arm"] == "copy" and "context_overflow" in (r.get("error") or "")]
    if ov:
        print(f"\n  copy runs that overflowed the context window: {len(ov)}")

    print(f"\nwrote {GEN}/tier3_gate.tex")
    return 0


if __name__ == "__main__":
    sys.exit(main())
