"""Aggregate the Tier-3 v3 sweep, and compare it against v2 (doc 22 §4).

v2 ran against the substrate as it was. It exposed two defects — an empty
plain-text outline, and a zero-match search that returned a bare `[]` — which
were fixed in the substrate. v3 re-runs the same grader over the same corpus
plus the real shapes (folder / bigcode / multihop). Reporting both is the
point: the delta *is* the finding.
"""

from __future__ import annotations

import json
import os
import sys
from collections import defaultdict

V2 = os.environ.get("TIER3_RUNS2", "bench/tier3/results/runs_v2.json")
V3 = os.environ.get("TIER3_RUNS3", "/tmp/tier3/out3/runs3.json")
GEN = os.environ.get("TIER3_GEN", "paper/generated")

SIX = ["text", "markdown", "code", "pdf", "voice", "video"]
REAL = ["folder", "bigcode", "multihop"]
ARMS = ["copy", "reference", "waggle"]


def load(p):
    return [r for r in json.load(open(p)) if not r.get("transport_error")]


def mean(xs):
    xs = list(xs)
    return sum(xs) / len(xs) if xs else 0.0


def stats(runs, key=lambda r: True):
    g = defaultdict(list)
    for r in runs:
        if key(r):
            g[r["arm"]].append(r)
    out = {}
    for a in ARMS:
        rs = g.get(a, [])
        out[a] = dict(
            n=len(rs),
            ok=mean(1 if r["correct"] else 0 for r in rs),
            tok=mean(r["in_tokens"] + r["out_tokens"] for r in rs),
            ing=mean(r["ingested"] for r in rs),
            usd=sum(r["dollars"] for r in rs),
            cov=mean(1 if r.get("coverage_met") else 0
                     for r in rs if r.get("coverage_met") is not None),
        )
    return out


def line(tag, s):
    return (f"  {tag:10} " + "  ".join(
        f"{a}={s[a]['ok']:.0%}/{s[a]['tok']:.0f}t/{s[a]['ing']:.0f}B" for a in ARMS))


def main() -> int:
    v3 = load(V3)
    print(f"v3 runs analysed: {len(v3)}\n")

    v2 = load(V2) if os.path.isfile(V2) else []
    if v2:
        a2 = stats(v2)
        a3six = stats(v3, lambda r: r["modality"] in SIX)
        print("=== the substrate fix: same six modalities, same grader ===")
        print(f"  {'':10} " + "  ".join(f"{a:>26}" for a in ARMS))
        for tag, s in (("v2 (before)", a2), ("v3 (after)", a3six)):
            print(f"  {tag:11} " + "  ".join(
                f"{s[a]['ok']:>7.1%} {s[a]['tok']:>7.0f}t {s[a]['ing']:>7.0f}B" for a in ARMS))
        d = a3six["waggle"]["ok"] - a2["waggle"]["ok"]
        print(f"\n  waggle accuracy: {a2['waggle']['ok']:.1%} -> {a3six['waggle']['ok']:.1%} "
              f"({d*100:+.1f} pts)   coverage {a3six['waggle']['cov']:.0%}")

    print("\n=== the real shapes (what people actually hand an agent) ===")
    for m in REAL:
        s = stats(v3, lambda r, m=m: r["modality"] == m)
        big = mean(r["artifact_bytes"] for r in v3 if r["modality"] == m)
        print(f"  {m:9} ({big/1000:.0f}KB) " + "  ".join(
            f"{a}={s[a]['ok']:.0%}/{s[a]['tok']:.0f}t/{s[a]['ing']:.0f}B" for a in ARMS))
        cw = s["copy"]["tok"] / s["waggle"]["tok"] if s["waggle"]["tok"] else 0
        print(f"            copy/waggle tokens = {cw:.1f}x   waggle coverage {s['waggle']['cov']:.0%}")

    print("\n=== overall (all 9 shapes) ===")
    s = stats(v3)
    for a in ARMS:
        print(f"  {a:9} correct={s[a]['ok']:.1%}  tokens={s[a]['tok']:.0f}  "
              f"ingested={s[a]['ing']:.0f}B  ${s[a]['usd']:.2f}")
    print(f"  waggle coverage={s['waggle']['cov']:.0%}   "
          f"copy/waggle tokens={s['copy']['tok']/s['waggle']['tok']:.1f}x  "
          f"bytes={s['copy']['ing']/max(s['waggle']['ing'],1):.0f}x")

    # ---- the receipt-as-predictor: does coverage still track correctness?
    print("\n=== does the receipt still predict the answer? (waggle arm) ===")
    w = [r for r in v3 if r["arm"] == "waggle" and r.get("coverage_met") is not None]
    for met in (True, False):
        sub = [r for r in w if r["coverage_met"] is met]
        if sub:
            print(f"  coverage {'MET  ' if met else 'unmet'}: n={len(sub):3}  "
                  f"correct={mean(1 if r['correct'] else 0 for r in sub):.1%}")

    # ---- emit the paper table
    os.makedirs(GEN, exist_ok=True)
    L = ["% generated by bench/tier3/analyze3.py (doc 22 §4) — do not edit",
         "\\begin{table*}[t]\n\\centering\\small",
         "\\caption{Nine artifact shapes, nine models, three turn-matched arms. The last "
         "three rows are the shapes real work has: a folder of many files, a $>$2000-line "
         "source file, and a multi-hop pointer chain no single grep can win. "
         "\\emph{ingest} is the artifact bytes that entered the context window. Coverage is "
         "the receipt's verdict --- a column the other arms structurally cannot have.}",
         "\\label{tab:tier3v3}\n\\renewcommand{\\arraystretch}{1.15}",
         "\\begin{tabular}{@{}l rr rr rr r@{}}\n\\toprule",
         "& \\multicolumn{2}{c}{\\textbf{copy}} & \\multicolumn{2}{c}{\\textbf{reference}} "
         "& \\multicolumn{2}{c}{\\textbf{waggle}} & \\\\",
         "\\cmidrule(lr){2-3}\\cmidrule(lr){4-5}\\cmidrule(lr){6-7}",
         "\\textbf{Shape} & ok & ingest & ok & ingest & ok & ingest & cov.\\\\",
         "\\midrule"]
    for m in SIX + REAL:
        s = stats(v3, lambda r, m=m: r["modality"] == m)
        if m == "folder":
            L.append("\\midrule")
        cov = "--" if s["waggle"]["n"] and m == "folder" else \
            f"{s['waggle']['cov']:.0%}".replace("%", "\\%")
        L.append(f"{m} & " + " & ".join(
            f"{s[a]['ok']:.0%}".replace("%", "\\%") + f" & {s[a]['ing']:.0f}" for a in ARMS)
            + f" & {cov}\\\\")
    L += ["\\bottomrule\n\\end{tabular}\n\\end{table*}"]
    open(f"{GEN}/tier3_shapes.tex", "w").write("\n".join(L) + "\n")
    print(f"\nwrote {GEN}/tier3_shapes.tex")
    return 0


if __name__ == "__main__":
    sys.exit(main())
