"""Aggregate the Tier-3 v2 sweep into the paper's tables (design doc 22 §4).

Emits into paper/generated/:
  tier3_modality.tex  — modality x arm: correctness, tokens, bytes ingested
  tier3_models.tex    — model x arm: correctness and cost, by family
  tier3_frontier.dat  — cost-vs-correctness frontier points (pgfplots)
"""

from __future__ import annotations

import json
import os
import sys
from collections import defaultdict

RUNS = os.environ.get("TIER3_RUNS2", "/tmp/tier3/out2/runs2.json")
GEN = os.environ.get("TIER3_GEN", "paper/generated")

MODS = ["text", "markdown", "code", "pdf", "voice", "video"]
ARMS = ["copy", "reference", "waggle"]
SHORT = {
    "claude-opus-4-1-20250805": "Opus 4.1",
    "claude-sonnet-4-5-20250929": "Sonnet 4.5",
    "claude-haiku-4-5-20251001": "Haiku 4.5",
    "gpt-5": "GPT-5",
    "gpt-5-mini": "GPT-5 mini",
    "gpt-4.1": "GPT-4.1",
    "gpt-4.1-mini": "GPT-4.1 mini",
    "gpt-4o": "GPT-4o",
    "gpt-4o-mini": "GPT-4o mini",
}


def mean(xs):
    xs = list(xs)
    return sum(xs) / len(xs) if xs else 0.0


def main() -> int:
    runs = json.load(open(RUNS))
    excluded = [r for r in runs if r.get("transport_error")]
    runs = [r for r in runs if not r.get("transport_error")]
    os.makedirs(GEN, exist_ok=True)
    print(f"runs analysed: {len(runs)}  (excluded transport errors: {len(excluded)})")

    # ---------- modality x arm
    g = defaultdict(list)
    for r in runs:
        g[(r["modality"], r["arm"])].append(r)

    L = ["% generated by bench/tier3/analyze2.py (doc 22 §4) — do not edit",
         "\\begin{table*}[t]\n\\centering\\small",
         "\\caption{The substrate across six modalities, nine models, three turn-matched arms. "
         "\\emph{copy} pastes the artifact's text; \\emph{reference} hands a path plus ordinary "
         "file tools; \\emph{waggle} hands a token and the consumer interrogates. "
         "\\emph{ingested} is the artifact bytes that actually entered the context window. "
         "Coverage is the receipts' verdict that the required region was consumed --- a column "
         "the other two arms structurally cannot have.}",
         "\\label{tab:tier3mod}\n\\renewcommand{\\arraystretch}{1.15}",
         "\\begin{tabular}{@{}l rrr rrr rrr r@{}}\n\\toprule",
         "& \\multicolumn{3}{c}{\\textbf{copy}} & \\multicolumn{3}{c}{\\textbf{reference}} "
         "& \\multicolumn{3}{c}{\\textbf{waggle}} & \\\\",
         "\\cmidrule(lr){2-4}\\cmidrule(lr){5-7}\\cmidrule(lr){8-10}",
         "\\textbf{Modality} & ok & tok & ingest & ok & tok & ingest & ok & tok & ingest "
         "& cov.\\\\",
         "\\midrule"]
    for m in MODS:
        cells = []
        for a in ARMS:
            rs = g.get((m, a), [])
            ok = mean(1 if r["correct"] else 0 for r in rs)
            tok = mean(r["in_tokens"] + r["out_tokens"] for r in rs)
            ing = mean(r["ingested"] for r in rs)
            cells.append(f"{ok:.0%}".replace("%", "\\%") + f" & {tok:.0f} & {ing:.0f}")
        w = g.get((m, "waggle"), [])
        cov = mean(1 if r.get("coverage_met") else 0 for r in w)
        L.append(f"{m} & " + " & ".join(cells) + f" & {cov:.0%}".replace("%", "\\%") + "\\\\")
    L += ["\\bottomrule\n\\end{tabular}\n\\end{table*}"]
    open(f"{GEN}/tier3_modality.tex", "w").write("\n".join(L) + "\n")

    # ---------- model x arm
    gm = defaultdict(list)
    for r in runs:
        gm[(r["model"], r["arm"])].append(r)
    L = ["% generated by bench/tier3/analyze2.py (doc 22 §4) — do not edit",
         "\\begin{table}[t]\n\\centering\\small",
         "\\caption{Correctness and cost per model. Anthropic token counts are approximate "
         "(the gateway strips usage); OpenAI counts are exact, and the arms are compared "
         "within a model, so the comparison does not turn on that.}",
         "\\label{tab:tier3mdl}\n\\renewcommand{\\arraystretch}{1.15}",
         "\\begin{tabular}{@{}lrrrr@{}}\n\\toprule",
         "\\textbf{Model} & copy & reference & waggle & waggle cov.\\\\",
         "\\midrule"]
    for mdl, short in SHORT.items():
        if not any((mdl, a) in gm for a in ARMS):
            continue
        cs = []
        for a in ARMS:
            rs = gm.get((mdl, a), [])
            cs.append(f"{mean(1 if r['correct'] else 0 for r in rs):.0%}".replace("%", "\\%"))
        w = gm.get((mdl, "waggle"), [])
        cov = f"{mean(1 if r.get('coverage_met') else 0 for r in w):.0%}".replace("%", "\\%")
        L.append(f"{short} & " + " & ".join(cs) + f" & {cov}\\\\")
    L += ["\\bottomrule\n\\end{tabular}\n\\end{table}"]
    open(f"{GEN}/tier3_models.tex", "w").write("\n".join(L) + "\n")

    # ---------- frontier
    with open(f"{GEN}/tier3_frontier.dat", "w") as f:
        f.write("tokens correct arm\n")
        for a in ARMS:
            rs = [r for r in runs if r["arm"] == a]
            f.write(f"{mean(r['in_tokens']+r['out_tokens'] for r in rs):.0f} "
                    f"{mean(1 if r['correct'] else 0 for r in rs):.4f} {a}\n")

    # ---------- console summary
    print("\nmodality x arm (correct% | tokens | ingested):")
    for m in MODS:
        row = []
        for a in ARMS:
            rs = g.get((m, a), [])
            row.append(f"{a}={mean(1 if r['correct'] else 0 for r in rs):.0%}/"
                       f"{mean(r['in_tokens']+r['out_tokens'] for r in rs):.0f}tok/"
                       f"{mean(r['ingested'] for r in rs):.0f}B")
        w = g.get((m, "waggle"), [])
        print(f"  {m:9} " + "  ".join(row) +
              f"  cov={mean(1 if r.get('coverage_met') else 0 for r in w):.0%}")
    print("\noverall:")
    for a in ARMS:
        rs = [r for r in runs if r["arm"] == a]
        print(f"  {a:9} correct={mean(1 if r['correct'] else 0 for r in rs):.1%} "
              f"tokens={mean(r['in_tokens']+r['out_tokens'] for r in rs):.0f} "
              f"ingested={mean(r['ingested'] for r in rs):.0f}B "
              f"${sum(r['dollars'] for r in rs):.2f}")
    print(f"\nwrote {GEN}/tier3_modality.tex, tier3_models.tex, tier3_frontier.dat")
    return 0


if __name__ == "__main__":
    sys.exit(main())
