//! Workspace automation. Two commands:
//!
//! - `cargo xtask lint-file-size` — enforce design doc `13 §1`: no source
//!   file exceeds 750 lines (paths under `tests/` are exempt). Approaching
//!   the cap is a design signal to split by concept, never by scissors.
//! - `cargo xtask gen-docs` — render `COMMANDS.md` from the operations
//!   catalog so the docs are a projection, not a copy (design doc `09 §2`).

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

mod vectors;

const MAX_LINES: usize = 750;

fn main() {
    let arg = std::env::args().nth(1).unwrap_or_default();
    let root = workspace_root();
    let result = match arg.as_str() {
        "lint-file-size" => lint_file_size(&root),
        "gen-docs" => gen_docs(&root),
        "gen-vectors" => vectors::generate(&root)
            .map(|()| println!("gen-vectors: wrote spec/vectors/"))
            .map_err(|e| format!("gen-vectors: {e}")),
        other => Err(format!(
            "unknown xtask `{other}` — try lint-file-size | gen-docs | gen-vectors"
        )),
    };
    if let Err(msg) = result {
        eprintln!("xtask: {msg}");
        std::process::exit(1);
    }
}

fn workspace_root() -> PathBuf {
    // xtask always lives one level below the workspace root.
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("xtask has a parent")
        .to_path_buf()
}

fn lint_file_size(root: &Path) -> Result<(), String> {
    let mut offenders = Vec::new();
    for dir in ["crates", "xtask"] {
        walk_rs(&root.join(dir), &mut |path| {
            if path.components().any(|c| c.as_os_str() == "tests") {
                return;
            }
            if let Ok(text) = std::fs::read_to_string(path) {
                if let Some(count) = file_too_long(&text) {
                    offenders.push(format!("{} ({count} lines)", path.display()));
                }
            }
        });
    }
    if offenders.is_empty() {
        println!("lint-file-size: all files within {MAX_LINES} lines");
        Ok(())
    } else {
        Err(format!(
            "files exceed the {MAX_LINES}-line cap (13 §1 — split by concept):\n  {}",
            offenders.join("\n  ")
        ))
    }
}

/// Returns `Some(line_count)` when the file breaches the cap.
fn file_too_long(text: &str) -> Option<usize> {
    let count = text.lines().count();
    (count > MAX_LINES).then_some(count)
}

fn walk_rs(dir: &Path, visit: &mut impl FnMut(&Path)) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            if path.file_name().is_some_and(|n| n == "target") {
                continue;
            }
            walk_rs(&path, visit);
        } else if path.extension().is_some_and(|e| e == "rs") {
            visit(&path);
        }
    }
}

fn gen_docs(root: &Path) -> Result<(), String> {
    let mut out = String::from(
        "# waggle — command & tool inventory\n\n\
         *Generated by `cargo xtask gen-docs` from the operations catalog \
         (`waggle-ops`). Do not edit by hand — edits belong in the catalog.*\n\n",
    );
    for op in waggle_ops::OPERATIONS {
        let surface = match op.surface {
            waggle_ops::Surface::Both => "CLI + MCP tool",
            waggle_ops::Surface::CliOnly => "CLI only",
        };
        let _ = writeln!(out, "## `{}` — {surface}\n\n{}\n", op.name, op.description);
        if !op.args.is_empty() {
            let _ = writeln!(out, "| arg | required | doc |\n|---|---|---|");
            for a in op.args {
                let _ = writeln!(out, "| `--{}` | {} | {} |", a.name, a.required, a.doc);
            }
            let _ = writeln!(out);
        }
        for e in op.forward {
            let _ = writeln!(out, "- forward → `{}`: {}", e.to, e.why);
        }
        for e in op.reverse {
            let _ = writeln!(out, "- reverse → `{}`: {}", e.to, e.why);
        }
        let _ = writeln!(out);
    }
    let dest = root.join("COMMANDS.md");
    std::fs::write(&dest, out).map_err(|e| format!("writing {}: {e}", dest.display()))?;
    println!("gen-docs: wrote {}", dest.display());
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn cap_is_inclusive_751_fails() {
        // CP-0 gate: the lint demonstrably fails a 751-line fixture.
        let ok = "x\n".repeat(MAX_LINES);
        assert_eq!(file_too_long(&ok), None);
        let too_long = "x\n".repeat(MAX_LINES + 1);
        assert_eq!(file_too_long(&too_long), Some(MAX_LINES + 1));
    }

    #[test]
    fn gen_docs_covers_every_operation() {
        let tmp = std::env::temp_dir().join(format!("waggle-xtask-{}", std::process::id()));
        std::fs::create_dir_all(&tmp).unwrap();
        gen_docs(&tmp).unwrap();
        let text = std::fs::read_to_string(tmp.join("COMMANDS.md")).unwrap();
        for op in waggle_ops::OPERATIONS {
            assert!(text.contains(op.name), "COMMANDS.md missing `{}`", op.name);
        }
        std::fs::remove_dir_all(&tmp).ok();
    }
}
