//! Emit reproducible pgfplots data files and LaTeX tables (design doc
//! `22 §7`). Every file is regenerated from source by `just bench-paper`,
//! so a reviewer re-derives each number rather than trusting a transcript.

use std::fmt::Write as _;
use std::fs;
use std::io;
use std::path::Path;

use crate::cost_model::{Costs, Scenario, SweepRow};
use crate::determinism::Report;

// Writing into a `String` via `fmt::Write` is infallible; this names that.
const INFALLIBLE: &str = "writing to an in-memory String cannot fail";

/// Write the cost-vs-size sweep as a pgfplots-ready `.dat` file.
pub(crate) fn write_cost_dat(path: &Path, rows: &[SweepRow]) -> io::Result<()> {
    let mut s = String::new();
    // A named header row (no comment lines) so pgfplots can read columns by
    // name: `\addplot table[x=s_kib, y=copy_cached]`. The tokenizer is
    // recorded in the figure/table captions, not here.
    writeln!(s, "s_kib copy_naive copy_cached waggle ratio").expect(INFALLIBLE);
    for r in rows {
        writeln!(
            s,
            "{:.0} {:.1} {:.1} {:.1} {:.2}",
            r.s_kib,
            r.costs.copy_naive,
            r.costs.copy_cached,
            r.costs.waggle,
            r.costs.ratio_vs_cached(),
        )
        .expect(INFALLIBLE);
    }
    fs::write(path, s)
}

/// Write a booktabs table of representative scenarios.
pub(crate) fn write_cost_table(
    path: &Path,
    rows: &[(String, Scenario, Costs)],
    tokenizer: &str,
) -> io::Result<()> {
    let mut s = String::new();
    s.push_str("% generated by waggle-bench (design doc 22 §2.1) — do not edit\n");
    s.push_str("\\begin{table}[t]\n\\centering\\small\n");
    writeln!(
        s,
        "\\caption{{Handoff cost in tokens under the strong (cached) copy \
baseline. Tokenizer: \\texttt{{{tokenizer}}}; cache discount $d=0.1$. The \
ratio is tokenizer-invariant.}}"
    )
    .expect(INFALLIBLE);
    s.push_str("\\label{tab:cost}\n\\renewcommand{\\arraystretch}{1.15}\n");
    s.push_str("\\begin{tabular}{@{}lrrrrrrr@{}}\n\\toprule\n");
    s.push_str(
        "\\textbf{Scenario} & $S$ & $H$ & $T$ & $R$ & copy\\,(cached) & waggle & ratio\\\\\n",
    );
    s.push_str("\\midrule\n");
    for (label, sc, c) in rows {
        writeln!(
            s,
            "{label} & {}\\,KB & {} & {} & {} & {:.0} & {:.0} & ${:.1}\\times$\\\\",
            sc.s_bytes / 1024,
            sc.holders,
            sc.turns,
            sc.revisions,
            c.copy_cached,
            c.waggle,
            c.ratio_vs_cached(),
        )
        .expect(INFALLIBLE);
    }
    s.push_str("\\bottomrule\n\\end{tabular}\n\\end{table}\n");
    fs::write(path, s)
}

/// Write the determinism result as LaTeX summary macros.
pub(crate) fn write_determinism(path: &Path, r: &Report) -> io::Result<()> {
    let verdict = if r.all_identical {
        "byte-identical"
    } else {
        "DIVERGED"
    };
    let mut s = String::new();
    s.push_str("% generated by waggle-bench (design doc 22 §2.2) — do not edit\n");
    writeln!(s, "\\newcommand{{\\benchDetTokens}}{{{}}}", r.tokens).expect(INFALLIBLE);
    writeln!(s, "\\newcommand{{\\benchDetEvents}}{{{}}}", r.events).expect(INFALLIBLE);
    writeln!(s, "\\newcommand{{\\benchDetPerms}}{{{}}}", r.permutations).expect(INFALLIBLE);
    writeln!(s, "\\newcommand{{\\benchDetVerdict}}{{{verdict}}}").expect(INFALLIBLE);
    // Fold latency is a wall-clock measurement; it is reported to stdout and
    // belongs in the hot-path table, not this committed artifact (which must
    // stay stable across runs). See `main::run_determinism`.
    fs::write(path, s)
}
